apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: server
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: gcr.io/cloudpark-e6cc4/server-deployment:1.0.1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
    role: master
    tier: backend
spec:
  ports:
  - port: 4000
    targetPort: 4000
  selector:
    app: server
    role: master
    tier: backend