apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-server-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dp-server
  template:
    metadata:
      labels:
        app: dp-server
    spec:
      containers:
      - name: container1
        image: gcr.io/cloudpark-e6cc4/server-new:new
        resources:
          requests:
            cpu: 100m          
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: server-side-configs